### PR TITLE
Attempt at fixing recent Travis JRuby build failures

### PR DESCRIPTION
**Pull request by obilodeau**
jruby-9k seems to provide a version no longer compatible with bundler.

See build failure in #292.

### CODE REVIEW

**Comment by obilodeau** [comment]
It fixed it! Will merge unless someone convinces me that it's wrong. Per policy, you have 24 hours :smile:

**Comment by Mogztter** [comment]
Nice!
Here's the link to the failing build: https://travis-ci.org/asciidoctor/asciidoctor-reveal.js/jobs/627564886
And the backtrace for reference:

```
NoMethodError: undefined method `[]' for nil:NilClass
  /home/travis/.rvm/gems/jruby-9.2.5.0/gems/bundler-2.1.2/lib/bundler/source/git/git_proxy.rb:90:in `version'
  /home/travis/.rvm/gems/jruby-9.2.5.0/gems/bundler-2.1.2/lib/bundler/source/git/git_proxy.rb:147:in `block in copy_to'
  org/jruby/RubyDir.java:399:in `chdir'
  /home/travis/.rvm/gems/jruby-9.2.5.0/gems/bundler-2.1.2/lib/bundler/shared_helpers.rb:52:in `block in chdir'
  /home/travis/.rvm/rubies/jruby-9.2.5.0/lib/ruby/stdlib/monitor.rb:226:in `mon_synchronize'
  /home/travis/.rvm/gems/jruby-9.2.5.0/gems/bundler-2.1.2/lib/bundler/shared_helpers.rb:51:in `chdir'
  /home/travis/.rvm/gems/jruby-9.2.5.0/gems/bundler-2.1.2/lib/bundler/source/git/git_proxy.rb:136:in `copy_to'
  /home/travis/.rvm/gems/jruby-9.2.5.0/gems/bundler-2.1.2/lib/bundler/source/git.rb:163:in `specs'
  /home/travis/.rvm/gems/jruby-9.2.5.0/gems/bundler-2.1.2/lib/bundler/definition.rb:764:in `block in converge_locked_specs'
  org/jruby/RubyArray.java:1792:in `each'
  /home/travis/.rvm/gems/jruby-9.2.5.0/gems/bundler-2.1.2/lib/bundler/definition.rb:750:in `converge_locked_specs'
  /home/travis/.rvm/gems/jruby-9.2.5.0/gems/bundler-2.1.2/lib/bundler/definition.rb:247:in `resolve'
  /home/travis/.rvm/gems/jruby-9.2.5.0/gems/bundler-2.1.2/lib/bundler/definition.rb:170:in `specs'
  /home/travis/.rvm/gems/jruby-9.2.5.0/gems/bundler-2.1.2/lib/bundler/definition.rb:158:in `resolve_remotely!'
  /home/travis/.rvm/gems/jruby-9.2.5.0/gems/bundler-2.1.2/lib/bundler/installer.rb:303:in `resolve_if_needed'
  /home/travis/.rvm/gems/jruby-9.2.5.0/gems/bundler-2.1.2/lib/bundler/installer.rb:84:in `block in run'
  /home/travis/.rvm/gems/jruby-9.2.5.0/gems/bundler-2.1.2/lib/bundler/process_lock.rb:12:in `block in lock'
  org/jruby/RubyIO.java:1154:in `open'
  /home/travis/.rvm/gems/jruby-9.2.5.0/gems/bundler-2.1.2/lib/bundler/process_lock.rb:9:in `lock'
  /home/travis/.rvm/gems/jruby-9.2.5.0/gems/bundler-2.1.2/lib/bundler/installer.rb:73:in `run'
  /home/travis/.rvm/gems/jruby-9.2.5.0/gems/bundler-2.1.2/lib/bundler/installer.rb:25:in `install'
  /home/travis/.rvm/gems/jruby-9.2.5.0/gems/bundler-2.1.2/lib/bundler/cli/install.rb:65:in `run'
  /home/travis/.rvm/gems/jruby-9.2.5.0/gems/bundler-2.1.2/lib/bundler/cli.rb:256:in `block in install'
  /home/travis/.rvm/gems/jruby-9.2.5.0/gems/bundler-2.1.2/lib/bundler/settings.rb:124:in `temporary'
  /home/travis/.rvm/gems/jruby-9.2.5.0/gems/bundler-2.1.2/lib/bundler/cli.rb:255:in `install'
  /home/travis/.rvm/gems/jruby-9.2.5.0/gems/bundler-2.1.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /home/travis/.rvm/gems/jruby-9.2.5.0/gems/bundler-2.1.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /home/travis/.rvm/gems/jruby-9.2.5.0/gems/bundler-2.1.2/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
  /home/travis/.rvm/gems/jruby-9.2.5.0/gems/bundler-2.1.2/lib/bundler/cli.rb:30:in `dispatch'
  /home/travis/.rvm/gems/jruby-9.2.5.0/gems/bundler-2.1.2/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
  /home/travis/.rvm/gems/jruby-9.2.5.0/gems/bundler-2.1.2/lib/bundler/cli.rb:24:in `start'
  /home/travis/.rvm/gems/jruby-9.2.5.0/gems/bundler-2.1.2/exe/bundle:46:in `block in <main>'
  /home/travis/.rvm/gems/jruby-9.2.5.0/gems/bundler-2.1.2/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
  /home/travis/.rvm/gems/jruby-9.2.5.0/gems/bundler-2.1.2/exe/bundle:34:in `<main>'
  org/jruby/RubyKernel.java:1007:in `load'
  /home/travis/.rvm/gems/jruby-9.2.5.0/bin/bundle:1:in `(root)'
  org/jruby/RubyKernel.java:1046:in `eval'
  /home/travis/.rvm/gems/jruby-9.2.5.0/bin/jruby_executable_hooks:24:in `<main>'
```

File: .travis.yml [hunk 1]
```diff
@@ -8,7 +8,7 @@ rvm:
 - 2.5
 - 2.4
 - 2.3
-- jruby-9k
+- jruby-head
```
Comment (Mogztter) [inline .travis.yml]: I think we should use the latest stable release:

```suggestion
- jruby-9.2.9.0
```
`jruby-head` resolves to `9.2.10.0-SNAPSHOT` and snapshots, by definition, are unstable.

Comment (mojavelinux) [reply .travis.yml]: Agree. We used jruby-head in the early days before 9.x was available. But that situation has long since passed.

Comment (obilodeau) [reply .travis.yml]: Alright, but this means tracking and understanding these upstream releases which I would rather not do... Can't they have a pointer to `$latest_stable`?

I'm going to go with 9.2.9.0 but I foresee that we will forget to keep it current.

Comment (mojavelinux) [reply .travis.yml]: I think RVM understands 9.2, which would cover you for quite a long time. Generally, I recommend following what Asciidoctor core does, so you won't have to track it outside of our own ecosystem.
