### PR TITLE
document preamble shown only on title slide (fixes #49, #43)

### LINKED ISSUE #49: document preamble (text after title before first section) is shown on every slide
A bug present in both deck.js and reveal.js related to the fact that block_preamble is processed after the title slide and will slip the content through inside a `<div>` which will not be properly nested inside the title's `<section>` element.

Already discussed here: http://discuss.asciidoctor.org/Using-Preambel-with-deck-js-scrambles-output-td2154.html

I don't think the solution of having the preamble in its own slide to be the proper one with regards to what one would expect when writing slides. I tried and failed to implement the second solution mentioned in the discussion.

@mojavelinux I tried listing attributes and can't find any attribute to match that would say: "this is the first slide". A section number would do. Also, it is unclear to me how to grab content of another block from within another template. Help appreciated :)

### PR DESCRIPTION
**Pull request by obilodeau**
As discussed in #49. Thanks for the guidance @mojavelinux. 

`@document.find_by` doesn't work on asciidoctor previous to 1.5.0 so I thought I mentioned minimum requirements in the README.

### CODE REVIEW

**Comment by mojavelinux** [comment]
Agreed. Now that GitHub is on 1.5.0, I think that's the minimum version of Asciidoctor the ecosystem should support.

**Comment by mojavelinux** [comment]
Maybe add a comment line in preamble.html.slim that explains the file is intentionally left blank?

**Comment by mojavelinux** [comment]
Btw, nice work!

**Comment by obilodeau** [comment]
Yes, I have no problem with the required version bump.

I added the comment. Good idea.

**Comment by mojavelinux** [comment]
Looks excellent!

**Comment by obilodeau** [comment]
I introduced a problem when there is no preamble.

```
undefined method `length' for nil:NilClass
  Use --trace for backtrace
```

**Comment by obilodeau** [comment]
I expected the result of find_by to be an empty array and not a nil. Fixed by a straight push to master (sorry about that): 3daa174

**Comment by mojavelinux** [comment]
The return value is fixed in the upcoming 1.5.3, but we'll have to live
with the nil guard in modules for now.
